import LocalizedStrings from "react-native-localization";

let strings = new LocalizedStrings({
  en: {
    Pleaseenterthe16digitcardnumber: "Please enter the 16-digit card number",
    plsenterid: "Please enter username",
    pleaseenterpassword: "Please enter password",
    idandpasswordareincorrect: "Username and password are incorrect",
    dashboard: "Dashboard",
    morning: "Morning",
    evening: "Evening",
    in: "Pending",
    out: "Out",
    driverid: "Driver username",
    login: "Login",
    viewroute: "VIEW ROUTE",
    dashboardscreen: "Dashboard",
    id: "Driver username",
    password: "Password",
    cancelreason: "Cancellation Reason",
    plsshareyouropinionabtourservices:
      "Please select the reason & add your notes",
    submit: "SUBMIT",
    visitinfo: "Visit Info",
    adrsinfo: "Address Info",
    contactinfo: "Contact Info",
    arrived: "Arrive",
    delivered: "Start",
    cancelled: "Cancel",
    getdirection: "Get Direction",
    profilenumber: "Main Profile Number",
    secondnumber: "Address mobile number",
    tripstarted: "Start trip",
    reservationnumber: "Reservation Number",
    expectedvisitend: "Actual Start Time",
    startdate: "Start Date",
    enddate: "End Date",
    visitstatus: "Visit Status",
    start: "Started",
    arrivaltime: "Arrival time",
    startvisit: "Start Deliver Time",
    endvisit: "Actual End Visit",
    visitduration: "Visit Duration",
    waitingduration: "Waiting Duration",
    chooseforreason: "Choose cancellation reason",
    drivernotavailable: "Driver not available",
    carbreakdown: "Car breakdown",
    workerdidntshowup: "Worker didn't show up",
    additionalcomments: "Additional comments",
    Completetrip: "Complete Trip",
    VisitNum: "Visit Num",
    new: "New",
    assigned: "Assigned",
    allocated: "Allocated",
    started: "Started",
    ended: "Ended",
    end:"End",
    customerpostponed: "Customer Postponed",
    customerCanceled: "Customer Canceled",
    companyCanceled: "Company Canceled",
    noWoman: "No Woman",
    wrongLocation: "Wrong Location",
    customerRefusesService: "Customer Refuses Service",
    Nodrivesisavailablefortoday: "No visits assigned to you today",
    Nodrivesisavailablefortonight: "No visits assigned to you tonight",
    cartripin: "Car Trip In",
    cartripout: "Car Trip Out",
    numberofhours: "Number Of Hours",
    carnumber: "Car Number",
    Employeename: "Employee Name",
    mobile1: "Mobile 1",
    mobile2: "Mobile 2",
    more: "More",
    supervisorname: "Supervisor Name",
    supervisorphone: "Supervisor Number",
    CustomerName: "Customer Name",
    District_Name:"District Name",
    Client_Address:"Client Address",
    Do_you_wish_to_cancel_your_trip:"Do you wish to cancel your trip?",
    Yes:"Yes",
    No:"No",
    Trip_Start:"Trip Start",
    Hold_Trip:"Hold Trip",
    Edit_Addr:"Edit Addr.",
    Finish:"Finish",
    Pick_Up:"Pick Up",
    not_start: "Not Start",
    inprogress: "In Progress",
    Completed: "Completed",
    Cancel: "Cancel",
    
  },
  ar: {
    Pleaseenterthe16digitcardnumber:
      "الرجاء إدخال رقم البطاقة المكون من 16 رقمًا",
    plsenterid: "الرجاء إدخال اسم المستخدم",
    pleaseenterpassword: "الرجاء إدخال كلمة المرور",
    idandpasswordareincorrect: "اسم المستخدم وكلمة المرور غير صحيحين",
    dashboard: "لوحة المعلومات",
    morning: "صباح",
    evening: "مساء",
    in: "الذهاب",
    out: "العودة",
    driverid: "اسم المستخدم للسائق",
    login: "تسجيل الدخول",
    viewroute: "عرض الطريق",
    dashboardscreen: "لوحة المعلومات",
    id: "اسم المستخدم",
    password: "كلمة المرور",
    cancelreason: "سبب إلغاء الزيارة",
    plsshareyouropinionabtourservices:
      "يرجى اختيار السبب للإلغاء مع اضافة ملاحظتك",
    submit: "إرسال",
    visitinfo: "تفاصيل الزيارة",
    adrsinfo: "تفاصيل العنوان",
    contactinfo: "ارقام التواصل",
    arrived: "تم الوصول",
    delivered: "بدء الزيارة",
    cancelled: "إلغاء الزيارة",
    getdirection: "احصل على الاتجاهات",
    profilenumber: "رقم التواصل الأساسي",
    secondnumber: "عنوان رقم الجوال",
    tripstarted: "بدء الرحلة",
    reservationnumber: "رقم العقد",
    expectedvisitend: "الوقت المتوقع لإنتهاء الزيارة",
    startdate: "وقت البدء",
    enddate: "وقت الانتهاء",
    visitstatus: "حالة الزيارة",
    start: "بدأت",
    arrivaltime: "وقت الوصول الفعلي",
    startvisit: "بدء الزيارة",
    endvisit: "انهاء الزيارة",
    visitduration: "مدة الزيارة",
    waitingduration: "مدة الانتظار",
    chooseforreason: "اختر السبب",
    drivernotavailable: "السائق غير متوفر",
    carbreakdown: "عطل السيارة",
    workerdidntshowup: "العاملة لم تظهر",
    additionalcomments: "إضافة ملاحظتك",
    Completetrip: "رحلة مكتملة",
    VisitNum: "رقم الزيارة",
    new: "جديد",
    assigned: "معينة",
    allocated: "مخصصة",
    started: "بدأت",
    ended: "انتهت",
    end:'انهاء الزيارة',
    customerpostponed: "تم التأجيل من قبل العميل",
    customerCanceled: "تم الإلغاء من قبل العميل",
    companyCanceled: "تم الإلغاء من قبل الشركة",
    noWoman: "لا توجد سيدة بالمنزل",
    wrongLocation: "موقع خاطئ",
    customerRefusesService: "رفض العميل الخدمة",
    Nodrivesisavailablefortoday: "لا يوجد لديك أي زيارات اليوم",
    Nodrivesisavailablefortonight: "لا يوجد لديك أي زيارات اليوم",
    cartripin: "رقم رحلة الذهاب",
    cartripout: "رقم رحلة العودة",
    numberofhours: "عدد الساعات",
    carnumber: "رقم السياره",
    Employeename: "اسم الموظف",
    mobile1: "رقم التواصل الأساسي",
    mobile2: "رقم التواصل للعنوان",
    more: "أكثر",
    supervisorname: "اسم المشرف",
    supervisorphone: "رقم المشرف",
    CustomerName: "اسم العميل",
    District_Name:"اسم الحي",
    Client_Address:"عنوان العميل",
    Do_you_wish_to_cancel_your_trip:"هل ترغب في إلغاء رحلتك؟",
    Yes:"نعم",
    No:"لا",
    Trip_Start:"بداية الرحلة",
    Hold_Trip:"عقد الرحلة",
    Edit_Addr:"تعديل العنوان",
    Finish:"ينهي",
    Pick_Up:"يلتقط",
    not_start: "لم يبدأ",
    inprogress: "قيد التقدم",
    Completed: "مكتمل",
    Cancel: "ملغى",




  },
});
export default strings;
